spring:
  sleuth:
    sampler:      probability: 1.0
  application:    name: servicio-oauth
server:
  port: 9100
  
#Se configura la ruta de Eureka.
eureka:  client:    serviceUrl:
      defaultZone: http://localhost:8761/eureka/